Week 3
darishenko/hybris-core pull request #4
Opened 2023-11-28 23:10 UTC by darishenko

2023-11-29 15:48 UTC, devjohnsmith1 requested changes

2023-11-29 15:48 UTC, devjohnsmith1 commented on bin/custom/concerttours/resources/concerttours-items.xml
> +                <attribute qualifier="daysUntil" type="java.lang.Long">
naming of an attribute is not clear: days until what? Isn't it better to rename to smth like daysUntillConcertLeft? + including a handler

2023-11-29 15:48 UTC, devjohnsmith1 commented on bin/custom/concerttours/resources/concerttours-items.xml
> +        <itemtype code="NotLoremIpsumConstraint" extends="AttributeConstraint"
why do we need a Constraint that checks for the exact text? Is it a check for some default text? Unclear

2023-11-29 15:48 UTC, devjohnsmith1 commented on bin/custom/concerttours/src/concerttours/events/AlbumSalesEventListener.java
> +import reactor.util.annotation.NonNull;
use javax.annotation.NonNull instead

2023-11-29 15:48 UTC, devjohnsmith1 commented on bin/custom/concerttours/src/concerttours/events/AlbumSalesEventListener.java
> +import reactor.util.annotation.NonNull;
+ check for other occurances in code

2023-11-29 15:48 UTC, devjohnsmith1 commented on bin/custom/concerttours/src/concerttours/facades/impl/DefaultBandFacade.java
> +import java.util.*;
.* imports all the classes of a package, which is not required here, please avoid this. You can check the IDEA settings for imports

2023-11-29 15:48 UTC, devjohnsmith1 commented on bin/custom/concerttours/src/concerttours/facades/impl/DefaultBandFacade.java
> +    protected String getImageURL(final BandModel bandModel, final MediaFormatModel format) {
@Nullable

2023-11-29 15:48 UTC, devjohnsmith1 commented on bin/custom/concerttours/web/webroot/WEB-INF/views/bandDetails.jsp
>  <h1>Band Details</h1>
please, put all string values in jsp's under localization properties and load on frontend with spring:message

2023-11-29 21:59 UTC, darishenko commented on bin/custom/concerttours/resources/impex/essentialdata-cronJobs.impex
0/30 min

2023-11-29 21:59 UTC, darishenko commented on bin/custom/concerttours/resources/impex/essentialdata-cronJobs.impex
> +; sendNewsCronJob; 0/10 * * * * ?
0/30 min

2023-12-01 11:00 UTC, devjohnsmith1 approved these changes

2023-12-01 11:13 UTC, merged